### ISSUE TITLE
error in resample_gaussian_states when running nascar.py 

### ISSUE THREAD

**Issue by amirhkhalilian** [slinderman/recurrent-slds#8]
Hi,
I'm trying to run nascar.py and get the following error! I've installed all packages from their git pages. I'd appreciate any help! Here is the error log:

Traceback (most recent call last):
  File "nascar.py", line 618, in <module>
    fit_slds(inputs, z_perm, x_init, y, mask, C_init)
  File "nascar.py", line 331, in fit_slds
    slds.resample_model()
  File "/pyhsmm/pyhsmm/models.py", line 442, in resample_model
    self.resample_states(num_procs=num_procs)
  File "/pyhsmm/pyhsmm/models.py", line 467, in resample_states
    s.resample()
  File "/recurrent-slds/rslds/states.py", line 175, in resample
    super(PGRecurrentSLDSStates, self).resample(niter=niter)
  File "/pyslds/pyslds/states.py", line 1262, in resample
    self.resample_gaussian_states()
  File "/recurrent-slds/rslds/states.py", line 179, in resample_gaussian_states
    super(PGRecurrentSLDSStates, self).resample_gaussian_states()
  File "/pyslds/pyslds/states.py", line 429, in resample_gaussian_states
    info_sample(*self.info_params)
  File "/lib/python3.8/site-packages/pylds/lds_messages_interface.py", line 65, in wrapped
    return func(*check(*args,**kwargs))
  File "/lib/python3.8/site-packages/pylds/lds_messages_interface.py", line 93, in _info_argcheck
    J_pair_11, J_pair_21, J_pair_22, J_node = \
  File "/lib/python3.8/site-packages/pylds/lds_messages_interface.py", line 24, in _ensure_ndim
    assert X.shape[0] == T
AssertionError

**Comment by amirhkhalilian** [comment]
installing pylds from source not pip seems to resolve the issue
